#alias ls='ls --color=auto'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'
#alias grep='grep --color=auto'
#alias fgrep='fgrep --color=auto'
#alias egrep='egrep --color=auto'
alias winHome='cd /mnt/d/Users/Joshua'
alias prog='cd ~/Computer-Science/162/'
alias CS='ssh jobetts@linux.cs.pdx.edu'
alias LAB='ssh jobetts@quizor1.cs.pdx.edu'
alias gitpp='./autoGit.sh' # Git Pull Push
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias tmux='tmux -f ~/dotfiles/.tmux.conf'
alias test='clear && g++ *.cpp -g && ./a.out'
